[user]
email = "rene@renerocks.ai"
name = "Rene Schallner"

[signing]
sign-all = false
# backend = "gpg"

[aliases]
b = ["branch"]
n = ["new"]

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
pager = "less"
